import { TransactionHistoryType } from './types';

export const transactionHistoryData: TransactionHistoryType[] = [
  {
    id: '1',
    amount: 120.5,
    date: '2025-02-07',
    description: 'Grocery Shopping',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '2',
    amount: 250.0,
    date: '2025-02-07',
    description: 'Salary Deposit',
    type: 'credit',
    accountName: 'John Doe',
  },
  {
    id: '3',
    amount: 50.75,
    date: '2025-02-07',
    description: 'Coffee',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '4',
    amount: 75.0,
    date: '2025-02-07',
    description: 'Online Purchase',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '5',
    amount: 199.99,
    date: '2025-02-07',
    description: 'Gym Membership',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '6',
    amount: 500.0,
    date: '2025-02-06',
    description: 'Freelance Payment',
    type: 'credit',
    accountName: 'John Doe',
  },
  {
    id: '7',
    amount: 30.0,
    date: '2025-02-05',
    description: 'Dinner',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '8',
    amount: 99.99,
    date: '2025-02-05',
    description: 'Subscription Renewal',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '9',
    amount: 45.0,
    date: '2025-02-05',
    description: 'Taxi Ride',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '10',
    amount: 1200.0,
    date: '2025-02-04',
    description: 'Bonus Payment',
    type: 'credit',
    accountName: 'John Doe',
  },
  {
    id: '11',
    amount: 60.0,
    date: '2025-02-04',
    description: 'Movie Night',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '12',
    amount: 15.0,
    date: '2025-02-04',
    description: 'Book Purchase',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '13',
    amount: 300.0,
    date: '2025-02-04',
    description: 'Freelance Work',
    type: 'credit',
    accountName: 'John Doe',
  },
  {
    id: '14',
    amount: 80.0,
    date: '2025-02-02',
    description: "Valentine's Gift",
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '15',
    amount: 25.0,
    date: '2025-02-02',
    description: 'Lunch',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '16',
    amount: 150.0,
    date: '2025-02-02',
    description: 'Shopping',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '17',
    amount: 75.0,
    date: '2025-02-01',
    description: 'Gaming Subscription',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '18',
    amount: 2000.0,
    date: '2025-02-01',
    description: 'Stock Investment',
    type: 'credit',
    accountName: 'John Doe',
  },
  {
    id: '19',
    amount: 40.0,
    date: '2025-02-01',
    description: 'Music Streaming',
    type: 'debit',
    accountName: 'John Doe',
  },
  {
    id: '20',
    amount: 600.0,
    date: '2025-02-01',
    description: 'Freelance Payment',
    type: 'credit',
    accountName: 'John Doe',
  },
];
